### PR TITLE
Contribution comments

### PR DESCRIPTION
**Pull request by JJHWAN**
#109 

Type hint에 대한 Contribution.md 를 만들었습니다.

### CODE REVIEW

**Review by jeesang7 — COMMENTED** [review]
https://github.com/Azure/azure-sdk-korean/commit/1e1fa2af4e90c15413c5bb456aeb4b395077388d

참고하셔서, __data/sidebars/general_sidebar.yml_ 에도 추가하시면 좋을 것 같습니다

**Comment by ianychoi** [comment]
Looks great! Two additional comments for @JJHWAN:

1. Would you change a commit message: "mend" to some other?
2. Please address as @jeesang7 mentioned

Thanks!

**Comment by JJHWAN** [comment]
두 분이 말씀하신 변경 모두 적용했습니다 
리뷰 감사합니다 :)

**Comment by ianychoi** [comment]
Thank you!

**Pull request merged**
